import streamlit as st


def app():

   
    st.title("Carbon Footprint: Definition and Reduction")

    st.header("What is Carbon Footprint?")
    st.write("A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by human activities, "
             "measured in units of carbon dioxide equivalent. It is a measure of the impact human activities have on the environment in terms of "
             "contributing to global warming and climate change.")

    st.header("Effects of Carbon Footprint")
    st.write("The increasing carbon footprint leads to several adverse effects on the environment, including:")
    st.write("- Global warming and climate change")
    st.write("- Melting ice caps and rising sea levels")
    st.write("- Changes in weather patterns, leading to more frequent and severe natural disasters")
    st.write("- Loss of biodiversity and habitat destruction")
    st.write("- Negative impacts on human health, including respiratory problems due to air pollution")

    st.header("Factors Contributing to Increased Carbon Footprint")
    st.write("There are several factors that contribute to the increase in carbon footprint, including:")
    st.write("- Burning of fossil fuels for energy production and transportation")
    st.write("- Deforestation and land use changes")
    st.write("- Industrial processes and manufacturing")
    st.write("- Agriculture, including livestock farming and methane emissions")
    st.write("- Waste generation and disposal")

    st.header("Ways to Reduce Carbon Footprint")
    st.write("Reducing carbon footprint is crucial for mitigating climate change and preserving the environment. Some ways to reduce carbon footprint include:")
    st.write("- Transitioning to renewable energy sources such as solar, wind, and hydroelectric power")
    st.write("- Improving energy efficiency in buildings, vehicles, and appliances")
    st.write("- Promoting sustainable transportation options such as walking, cycling, and public transit")
    st.write("- Adopting eco-friendly practices in agriculture and forestry")
    st.write("- Reducing, reusing, and recycling waste materials")
    st.write("- Supporting policies and initiatives aimed at carbon reduction and environmental protection")


